







init python:

    def clamp(n, smallest, largest):
        return max(smallest, min(n, largest))

    def limit_stats():
        
        store.Chuck_Friendship = max(min(Chuck_Friendship,10), 0)
        store.August_Friendship = max(min(August_Friendship,10), 0)
        store.Sam_Friendship = max(min(Sam_Friendship,10), 0)
        store.Warren_Friendship = max(min(Warren_Friendship,10), 0)
        store.Jacob_Friendship = max(min(Jacob_Friendship,10), 0)
        store.Mina_KLove = max(min(Mina_KLove,10), 0)
        
        store.Rosalind_Libido = max(min(Rosalind_Libido,20), 0)
        
        store.toughness = max(min(toughness,30), 0)
        store.Kathleen_Affection = max(min(Kathleen_Affection,30), 0)
        
        store.Killian_Bromance = max(min(Killian_Bromance,40), 0)
        store.Rosalind_Affection = max(min(Rosalind_Affection,40), 0)
        store.Mina_Affection = max(min(Mina_Affection,40), 0)
        store.Hana_Affection = max(min(Hana_Affection,40), 0)
        store.Veronica_Affection = max(min(Veronica_Affection,40), 0)
        store.Felicia_Affection = max(min(Felicia_Affection,40), 0)

    config.python_callbacks.append(limit_stats)



    mcf = "Edwin"
    mcl = "Turner"
    id_greed = False
    id_power = False
    id_lust = False

    trait_inquisitive = False
    trait_tireless = False
    trait_governor = False

    history_firestarter = False
    history_voyeur = False
    history_stickyFingers = False

    perk_strongman = False
    perk_socialButterfly = False
    perk_socialChameleon = False

    toughness = 13
    investigationPoints = 0



    Killian_Bromance = 11




    Rosalind_Affection = 8
    Rosalind_Libido = 0
    roseFlag = False
    roseTakeAdvantage = False
    roseTAapology = False
    Rosalind_Relations = "Carnation"
    roseDealFullAcceptance = False




    Felicia_Affection = 8
    Felicia_Confidence = 0
    feliciaSex = False
    feliciaFlag = False
    Felicia_Relations = "Carnation"



    Veronica_Affection = 5
    Veronica_Horniness = 0
    VeroFlag = False
    Veronica_Relations = "Carnation"
    veronicaFriend = False


    Mina_Affection = 8
    Mina_KLove = 7
    Mina_BiCurious = 0
    minaFlag = False
    minaCheat = False
    minaBreakOff = False
    minaCleanStart = False
    Mina_Relations = "Best friend's girl"


    Hana_Affection = 8
    Hana_Anger = 3
    hanaFlag = False
    Hana_Relations = "Co-worker"
    hanaGF = False



    Kathleen_Affection = 8
    Kathleen_Trust = 0
    kat_polite = False
    Kathleen_Relations = "Boss"


    August_Friendship = 3
    augustTrust = False


    Jacob_Friendship = 3


    Warren_Friendship = 0


    Chuck_Friendship = 5
    chuckTrust = True
    chuck_polite = False
    chuck_uncle = False


    Sam_Friendship = 3


    prKillianAnnoyed = False
    prRoseTAkiss = False
    prTakeAdvantage = False
    prTAapology = False
    prDiscoFeliciaPinch = False
    prBirthdayMinaGift = False
    prGetOutOfJail = False
    prPoolJumpKillian = False
    prThreesomePicture = False
    prVero_Facial = False
    feliciaDaddy = False


    w1Spin = False
    w1VeroGonzo = False
    w1FelGonzo = False
    w1RoseGonzo = False
    w1GonzoScore = 0
    gonzoQuestions = 0
    w1GonzoReward = False
    w1RosalindScore = 0
    w1FeliciaScore = 0
    w1VeronicaScore = 0
    w1VeronicaPCUndress = False
    w1MinaLie = False
    w1MinaCaught = False
    MinaOutfitPro = False
    MinaOutfitCute = False
    MinaOutfitSexy = False
    rosePolite = False
    roseHelpSex = False
    roseHelpNeed = False
    roseHelpMom = False
    feliciaDinnerDecline = False
    jacobHarpVouch = False
    w1HanaTalkPlay = False
    w1HanaSingleMother = False
    minaGym = False
    w1VeroHorniness = 0
    w1AugustTrust = False
    w1RosalindPhoto = False
    w1ExTimeBlock = "A"
    w1ExBusinessRepeat = False
    w1ExJacobRepeat = False
    w1ExTenorRepeat = False
    w1ExDickhead = False
    w1ExDaliaEntertain = False
    w1ExChuckRepeat = False
    w1ExKatRepeat = False
    w1ExHanaRepeat = False
    w1ExSecurityRoomUnlock = False
    w1KatQuestionsRole = False
    w1KatQuestionsSocialize = False
    w1KatQuestionsScoring = False
    w1KatQuestionScore = 0
    w1ExWarrenGoneScore = 0
    w1ExHarrassmentRepeat = False
    w1ExJacobBRepeat = False
    w1ExVIPLoungeComplete = False
    w1ExMamaBoyRepeat = False
    w1ExChuckBRepeat = False
    w1ExSecurityRoomSpyingRepeat = False
    w1ExVeroRepeat = False
    w1ExInControl = False
    w1ExDeferential = False
    w1ExAttentive = False
    w1ExWorship = False
    w1ExTender = False
    w1ExNasty = False
    w1ExTease = False
    w1ExGame1Ejaculation = False
    w1ExVeroPissedOn = False
    w1ExIntuitionGameWinnerRose = False
    w1ExIntuitionGameWinnerFel = False
    w1ExIntuitionGameWinnerVero = False
    w1ExGame2WinnerRose = False
    w1ExGame2WinnerFel = False
    w1ExGame2WinnerVero = False
    w1ExShockPoints = 0
    w1ExGame2LoserFel = False
    w1ExGame2LoserRose = False
    w1ExGame2LoserVero = False
    w1ExGame3Avoid = False
    w1VeronicaDRMolest = False


    w2AlicePhotos = False
    w2KillianBet = False
    w2Bullshit = False
    DP = 0
    minaBully = False
    w2FetishChoke = False
    w2FetishEdging = False
    w2FetishObjectify = False
    hanaFriendFlag = False
    w2HanaSex = False
    VeronicaPentUp = False
    w2KatAnger = False
    w2MinaFashionShow = False
    w2MinaFamilyPhoto = False
    w2MinaGlamourMagazine = False
    w2MinaMinaDad = False
    w2MinaKillian = False
    w2MinaBridesOfTheHunt = False
    w2MinaArchery = False
    w2ExJuliet = False
    w2MinaFamilyPhotoQ = False
    w2MinaConversate = 0
    w2MinaDadQ = False
    w2MinaMagazineQ = False
    w2MinaArcheryQ = False
    w2MinaJulietQ = False
    w2MinaBotHQ = False
    w2MinaScenePoints = 0
    w2MinaKiss = False
    w2HarpDog = False
    w2HarpUncle = False
    w2HarpDad = False
    w2KatSex = False
    w2KatSexSub = False
    w2HarpRainCheck = False
    w2KatBottom = False
    w2KatTop = False
    w2HarperSolo = False
    w2RoseFirst = False
    w2RosalindTeased = False
    w2RosalindParkTunnel = False
    w2RoseParkOldman = False
    w2RoseGag = False
    w2RosaMean = False
    w2RosaCreative = False
    w2RosaKind = False
    w2RosaCreativeMenu = False
    w2VeroToplessPose1 = False
    w2VeroToplessPose2 = False
    w2VeroToplessPose3 = False
    w2VeroToplessPose4 = False
    w2VeroToplessScore = 0
    w2VeronicaDog = False
    w2VeronicaHeated = False
    w2VeronicaMean = False
    w2VeronicaTBag = False
    w2VeronicaScratch = False
    w2VeronicaSquirm = False
    w2EdwinFacial = False
    w2VeronicaTop = False
    w2HanaHump = False
    w2RoseShootPoints = 2
    w2VeroShootPoints = 1
    w2FelShootPoints = 0
    w2VeronicaShameless = False
    w2MinaIanCover = False
    w2MinaWorkQ = False
    w2MinaFlagVent = False
    w2MinaPat = False
    w2FeliciaPacked = False
    w2FeliciaExtra = False
    w2FeliciaHigh = False
    w2FeliciaGrab = False
    w2FeliciaDegrade = False
    feliciaAnger = False
    w2FeliciaImpressed = False
    edwinAnal = False
    feliciaSugarBaby = False
    rosalindSolution = False
    rosalindFelSolution = False
    rosalindKatSolution = False
    rosalindKatSolutionFree = False
    rosalindAugSolution = False
    rosalindKilSolution = False
    w2KillianRoseOffer = False
    killianHeadsUp = False
    w2VeronicaExposed = False
    w2TIWarrenDaliaRepeat = False
    w2TINicoletteRepeat = False
    harperOption = False
    w2TIAugustRepeat = False
    w2TITimeBlock = "A"
    w2TIDaliaNicoFirst = False
    w2TIDaliaNicoSecond = False
    w2TIAugustLeft = False
    w2TINavUnlock = False
    w2TIDaliaNicoLeft = False
    w2TINavUnlock = False
    w2TINurseRepeat = False
    w2TIChessGameRepeat = False
    w2DressingRoomFinished = False
    w2TIHarperCSeen = False
    w2MinaDistract = False
    w2MinaBetWin = False
    w2MinaMess = False
    w2MinaLovers = False
    w2MinaPush = False
    w2FeliciaAbort = False
    w2FightBranch = 0
    w2RosalindPhoto = False
    w2ExTimeBlock = "A"
    w2ExAugustARepeat = False
    w2ExAugustBRepeat = False
    w2ExYooriARepeat = False
    w2ExSamsonARepeat = False
    w2ExIsaakARepeat = False
    w2ExDaliaARepeat = False
    w2ExVeronicaMingleARepeat = False
    w2ExRosalindMingleARepeat = False
    w2ExFeliciaMingleARepeat = False
    w2ExYooriBRepeat = False
    w2ExJacobARepeat = False
    w2ExWarrenARepeat = False
    w2ExJacobBRepeat = False
    w2ExEmmaFavor = "unknown"
    w2ExWhippedOut = False
    w2ExRosalindKissDemo = False
    w2ExSexRoomUnlock = False
    w2ExVincenzoB1 = False
    w2ExVincenzoB2 = False
    w2ExChuckBRepeat = False
    w2ExIanAbelSophiaBRepeat = False
    w2DaliaBRepeat = False
    w2ExWarrenBRepeat = False
    w2ExEmmaBRepeat = False
    w2ExMercedesBRepeat = False
    w2ExNicoBRepeat = False
    w2ExDaliaBRepeat = False
    w2ExMercedesBRepeat = False
    w2ExKathleenBRepeat = False
    w2ExLezSeen = False
    w2ExEmmaFavorIan = False
    w2ExEmmaFavorChuck = False
    w2ExEmmaFavorSolo = False
    w2FelHalfMeasure = False
    w2ExRoseIanSex = False
    w2ExSnowball = False
    w2ExKatFelicia = False
    w2ExKatRosalind = False
    w2ExKatVeronica = False
    w2ExPointsFelicia = 0
    w2ExPointsRosalind = 0
    w2ExPointsVeronica = 4
    w2ExMomConcern = False
    w2ShootWinnerFel = False
    w2ShootWinnerRose = False
    w2ShootWinnerVero = False
    w2ExSearch = False
    w2ExEndingMina = False
    w2ExEndingVeronica = False
    w2FelSex = False
    w2ExKathleenAdvice = False
    w2ExVeronicaHome = False
    w2ExLosersAll = False
    w2ExLoserDuo = False
    w2ExLoserFelicia = False
    w2ExLoserVeronica = False
    w2ExWinnerFelicia = False
    w2ExWinnerRosalind = False
    w2ExWinnerVeronica = False
    w3MinaPickle = False
    w2ExEndingKathleen = False
    w2ExEndingVictoria = False
    w2RoseMomMet = False


    w3IanDealReveal = False
    ianIntrospect = False
    w3HanaDP = 0
    w3HanaMutual = False
    w3HanaSweet = False
    w3HanaFH = False
    w3MinaTransparent = False
    w3NotMessy = False
    hanaTwoTime = False
    w3HanaUnconditional = False
    w3MinaOpening = False
    w3RosalindMeanShock = False
    w3VeronicaMeanShock = False
    w3PromoShockFullSadism = False
    w3FeliciaMeanShock = False
    w3SophiaPolite = False
    w3HagHandie = False
    w3KathleenLezTold = False
    w3MinaRejection = False
    w3MinaSayMyName = False
    w3MinaDaddy = False
    w3KatPromoFinish = False
    w3SophiaPromoFinish = False
    w3AbelControl = False
    w3Recollection = False
    w3AliceSeen = False
    w3MinaHotelFucked = False
    w3HanaCutieCall = False
    w3MinaCutieCall = False
    w3CarnationCallRosalind = False
    w3CarnationCallFelicia = False
    w3CarnationCallVeronica = False
    w3VeroBarDate = False
    w3EdwinSuckerPunched = False
    w3EdwinKnockedOut = False
    w3RosalindConfrontationAmiable = False
    w3RCKnockout = False
    w3RCDoubleAssBeat = False
    w3RCTussled = False
    w3RCSuckerPunched = False
    w3RCThreatened = False
    w3RCTalkedDown = False
    w3RosalindViolentSolution = False
    w3RosalindConnectionSolution = False
    w3RosalindMassaged = False
    w3VeroHighness = False
    w3VeronicaWorship = False
    w3ChallengeAccepted = False
    w3RoseStayLewd = 0
    w3RoseStayMean = 0
    w3VeronicaSex = False
    w3AliceOffer = False
    w3VeronicaShared = False
    hanaCheat = 0
    w3HanaClubKiss = False
    w3HanaBrothelRP = False
    w3ChuckClose = False
    w3KimberReality = False
    w3KimberWrong = False
    w3DariusFakeName = False
    w3MCThreesomeCherryPopped = False
    w3FeliciaPlatonic = False
    w3VeronicaWingman = False
    w3RayKiss = False
    w3LucyAffability = 0
    w3LucyPressure = 0
    w3LucyConvoPoint = 0
    w3CoincidenceAsk = False
    w3LucyHowUDoin = False
    w3LucyHowUDoin = False
    w3LucyEricAsk = False
    w3LucyLezTease = False
    w3CoincidenceAskTwice = False
    kissAttempt = False
    kissAttempt2 = False
    w3FeliciaEricWarn = False
    w3LucyConfront = False
    w3EricTalked = False
    w3FeliciaIdle = False
    w3LizaBlackMail = False
    w3ActuallyBlackmail = False
    w3FeliciaDeniseConvinced = False
    w3LucyTouch = False
    w3KathleenFeliciaReveal = False
    w3MinaWantsToWatch = False
    w3FeliciaLoseControl = False
    w3FeliciaRomanceFocus = False
    w3FeliciaThreesomeControl = False
    w3FeliciaChoke = False
    w3LucyRelationshipOffer = False
    w3HanaFriendEncourage = False
    w3FeliciaSoloEnd = False
    w3FeliciaMinaThreesomeEnd = False
    w3FeliciaArtSoloFriendEnd = False
    w3FeliciaArtPrematureEnd = False
    w3AndreaRizz = 0
    w3AndreaFoolAround = False
    w3AndreaDemean = False
    w3VickyRabbitHole = 0
    w3RTalkRapport = 0
    w3RTalkLubrication = 0
    w3RTalkOpenness = 0
    w3RosalindDateDate = False
    w3RTalkEducation = False
    w3RTalkReligion = False
    w3RTalkScamming = False
    w3RosalindRomanticSex = False
    w3RosalindEndlessBJWorks = False
    w3RosalindInviteStay = False
    w3WarrenStandOff = False
    w3KatPrincessPlay = False
    w3KatSnare = False
    w3MinaJealous = False
    w3VeronicaMinaLezPush = False
    w3RockShowIanTalk = False
    w3IanMinaTalk = False
    w3RockShowRosaPath = False
    w3RockShowBroPath = False
    w3RockShowBartenderPath = False
    w3RockShowHanaPath = False
    w3RockShowVeronicaPath = False
    w3RockShowMinaHanaPath = False
    w3MinaRockShowKiss = False
    w3RockShowJammed = False
    w3RockShowFeliciaPath = False
    w3RockShowMinaBarEnding = False
    w3RockShowVeroMinaMadeOutExtra = False
    w3PaintingReveal = False
    hanaMinaFlag = False
    w3RockShowHanaKiss = False
    ianVickyTruth = False
    vickyVideoDeletus = False
    w3RockShowBartenderFingerFuck = False
    w3MomToldHana = False
    w3MomToldMina = False
    w3MomToldFelicia = False
    w3MomToldVeronica = False
    w3AndreaBark = False
    w3RosalindVibing = False
    w3KathleenTestAbort = False
    w3KatPhoto = False
    w3RockShowMinaHanaKiss = False
    w3SophApologyPush = False
    sophiaRapport = 0
    w3SoloVickyVisit = False
    w3DuoVickyVisit = False
    w3HanaMomMeet = False
    w3MinaPreExHang = False
    w3MinaPreExDidNotPickUp = False
    w3ExKimberStage1Repeat = False
    w3ExJacobStage1Repeat = False
    w3ExHallwayRosalindFlirtSeen = False
    w3ExCarnationDressingRoomVeronica = False
    w3ExCarnationDressingRoomDuo = False
    w3ExSammyVinceStage1Repeat = False
    w3ExHallwaySammyVinceMove = False
    randint = 0
    w3ExKimberGone = False
    w3VeronicaGetOwned = False
    w3ExBarSluttyGaggleRepeat = False
    w3ExBarHarperStage1Repeat = False
    w3ExBarThomasRepeat = False
    w3ExBarProgress = 0
    w3ExBarJimEricRepeat = False
    w3ExBarMihirCompany = False
    w3ExSaunaUnlocked = False
    w3ExAO2Kimber = False
    w3ExAugustHanaIntroduction = False
    Elias_Friendship = 0
    Allison_Interest = 0
    w3ExAOAllisonSeen = False
    w3ExAOAugustSoloRepeat = False
    w3ExMR2Repeat = False
    w3Stage2Time = 0
    w3ExAOHanaLeft = False
    w3SRIntroSeen = False
    w3ExSREmpty = False
    w3EHIntroSeen = False
    w3ExKristoffMet = False
    w3ExPoolFrankRepeat = False
    w3ExHallwayLucySeen = False
    w3ExHallway2KatWarrenRepeat = False
    w3ExHallway2WheresLucyRepeat = False
    w3ExHallway2MihirRepeat = False
    w3ExWIPStage2Repeat = False
    w3ExAugustTalk = False
    w3ExAugustStage3Repeat = False
    w3ExAllisonHaveGF = False
    w3ExBar3AllisonLeft = False
    w3ExAllisonPutInPlace = False
    w3ExBar3KimberRepeat = False
    w3ExBar3SophiaRepeat = False
    w3ExKOStage3Empty = False
    w3ExHanaKatTalk = False
    w3ExHanaPhotoshoot = False
    w3ExKatHallwaySeen = False
    w3ExKatFlirt = False
    w3ExIsaakPromise = False
    w3ExHallwayLucyGone = False
    w3ExHDROPen = False
    w3ExLucyNow = False
    w3ExKOStage3Seen = False
    w3ExLucyCheatingPlay = False
    w3LucyArtKiss = False
    w3LucyGrope = False
    w3LucySupergrope = False
    Lulu = False
    w3ExVRFirst = False
    w3ExVRWrestlingRepeat = False
    w3ExVRMMRepeat = False
    w3ExLucyFuck = False
    w3ExFeliciaTalk = False
    w3ExEndSkip = False
    w3ExDidDrugs = False 
    w3AllisonHonest = False
    w3ExAllisonTender = False
    graceRevenge = False
    badIdeaBro = False
    w3ExFelForewarnedSortOf = False

    met_august = False
    met_felicia = False
    met_hana = False
    met_isaak = False
    met_jacob = False
    met_kathleen = False
    met_lucy = False
    met_mina = False
    met_rosalind = False
    met_samson = False
    met_veronica = False
    met_warren = False
    met_spider = False
    met_dalia = False
    met_harper = False
    met_jerrica = False
    met_grace = False
    met_abel = False
    met_sophia = False
    lucyProstitute = False
    history_august = "I don’t quite know what to make of him. He seems nice enough, but there’s this impalpable shadiness that clings to him like a newborn baby. It’s probably because he dresses like a two-bit pimp and manages a sex club - just to hazard a guess. "
    history_chuck = "Dr. Chuck is the uncle of my best friend and my personal mentor through high school. Short of male role models growing up, he gregariously filled the role with an open heart. Has a bit of an American exceptionalism attitude, which makes him kinda an asshole, but our familiarity means I don’t hold his more pig-headed opinions against him."
    history_felicia = ""
    history_hana = "Hana strikes me as a woman out of place at the Carnation Club, but then again, I guess so am I. I wonder what her story is."
    history_isaak = "A particularly slimy member of the Carnation Club, he sponsored Lucy as a candidate for the summer exhibition. Knowing he's in charge of the admissions office for the most prestigious, snobby private school in the tri-state area does fill me with a twisted sense of glee though."
    history_jacob = "A bouncer at the Carnation Club, I really don’t know that much about him yet besides that he seems like a nice guy."
    history_kathleen = "Part owner of the Carnation Club, who handles the human resources. It’s clear from the clothes she wears and the confidence she carries herself with that she comes from money. This lady simply oozes class. Still, she seems nice on the surface, if not a little too flirty."
    history_killian = "Perhaps owing to our extensive personal history, Killian is a hard person for me to describe. I’ve known him since he was the polar opposite of how he is now, from a shy kid with self-confidence issues to... well, how he is now.  He and I used to be inseparable, and my own mother even became something of a parental figurehead to him thanks to his own parents' “hands-off” approach. "
    history_lucy = "A hopeful prospect for the Carnation Club's summer exhibition, she seeks to get her son admitted to the very school she teaches at."
    history_mina = "My best friend's girlfriend, she has a sunny disposition and a bubbly personality ill-suited to Ian's womanizing ways."
    history_rosalind = ""
    history_samson = "A member of the Carnation Club and former B-movie action star, Samson strikes me as a man of hot air and bluster, but he does have a certain charm and coolness that invites you to live vicariously through his words."
    history_veronica = "A prospective contestant for the Club's summer exhibition, she seeks to escape the money troubles facing her gym. Come to think of it, I actually think I might've seen her in a local commercial or two."
    history_victoria = "The most important person in my life, my mother. She’s a kind, strong woman who suffered through indignity to limit the impact of my father’s death on my lifestyle.  I owe my distaste for incomprehensible Italian movies to her."
    history_warren = "The senior member of the Carnation Club’s two-man security team, he seems nice enough from his introduction, but sheer animal instinct practically screams to me he's not someone you'd want to fuck with."
    history_dalia = "Dalia was introduced to me as the club's head house girl. It left me wondering if that means she's queen of the prostitutes or something."
    history_harper = "A woman of seemingly few words, Harper is one of the club's house girls. Which, from what I gather, is the club's sanitized way of saying full-time prostitute."
    history_spider = "A bass player and Hana's bandmate, Spider -as he nicknamed himself- seems like a pretty solid dude. Even with his colorful personality, he somehow manages to stand out the least among the trio."
    history_jerrica = "The front woman of Eros Massacre and Spider's girlfriend, she's got a larger-than-life personality that rivals Hana's."
    history_grace = "Ian's mother, who I hadn't seen in a few years. She seemed more approachable than I had previously remembered, but that evaporated as soon as the two of us were alone. She wants me to convince Ian to go to college, in exchange for some nebulous compensation."
    history_abel = "CEO and co-founder of Waller Scientific International, Abel van Doren is regarded as a pioneer in the field of synthetic organic chemistry and pharmacology. What little I know about him is limited to his carefully curated public persona, but he is equally regarded for his philanthropic efforts as much as his professional achievements. The fact he's here at the club betrays that..."
    history_sophia = "Turns out the beautiful woman who is always with Dr. Van Doren is Dr. Sophia Lundgren and she stands to inherit the man's position once he retires from Waller Scientific International."
    unread_august = True
    unread_chuck = True
    unread_felicia = True
    unread_hana = True
    unread_isaak = True
    unread_jacob = True
    unread_kathleen = True
    unread_killian = True
    unread_lucy = True
    unread_mina = True
    unread_rosalind = True
    unread_samson = True
    unread_veronica = True
    unread_victoria = True
    unread_warren = True
    unread_spider = True
    unread_dalia = True
    unread_harper = True
    unread_jerrica = True
    unread_grace = True
    unread_abel = True
    unread_sophia = True
    profilehubunlock = False
    statisticsunlock = False
    date = "introNight"
    prVicDinner_score = 0
    prVicDinner_work = False
    prVicDinner_date = False
    prVicDinner_movies = False
    prVicDinner_compliment = False
    prAugQuestions = 0
    prAugQuestions_sex = False
    prAugQuestions_work = False
    prAugQuestions_schedule = False
    prAugQuestions_woman = False
    prRoseDateHobby = False
    prRoseDateSponsor = False
    prYesSir = False
    rosePN = "[mcf]"
    felPN = "[mcf]"
    felSN = ""
    roseSN = "sir"
    mcRoseSN = "Rose"
    veroSN = "sir"
    verPN = "[mcf]"
    hanaPN = "[mcf]"
    katPN = "[mcf]"
    MinaPN = "[mcf]"
    photoalbum_1 = False
    discoMinaLeft = False
    discoDanceMina = False
    discoDanceGroup = False
    discoMinaBathroom = False
    discoMinaUpper = True
    discoFelUpper = True
    drinkGot = False
    drinkGet = False
    discoMinaConsole = False
    drinkGood = False
    drinkNeutral = False
    drinkBad = False
    discoFelInvite = False
    discoKillianWarning = False
    prDiscoFelTit = False
    prAfterParty = False
    roseMarried = False
    roseSeduceFlag = False
    roseGonzoTheme = False
    roseGonzoExperience = False
    roseGonzoFantasy = False
    roseGonzoPositions = False
    roseGonzoTaste = False
    felGonzoTheme = False
    felGonzoWildest = False
    felGonzoTaste = False
    felGonzoSexLife = False
    felGonzoPosition = False
    veroGonzoTheme = False
    veroGonzoExperience = False
    veroGonzoFantasy = False
    veroGonzoTaste = False
    veroGonzoRelationship =  False
    w1FelTits = False
    w1FelAss = False
    feliciaDaddy = False
    w1HanaInterest = False
    w1HanaBandPath = False
    w1HanaBikePath = False
    w1RoseSNMenu = False
    w1mcRoseSN = False
# Decompiled by unrpyc: https://github.com/CensoredUsername/unrpyc
