name: 👿👿👿👿🔥

on:
  workflow_dispatch:

jobs:
  translate1:
    name: Translate Pattern 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          cd ..
          pip install googletrans==4.0.0rc1 requests
      - run: python3 py/translate1.py
      - uses: actions/upload-artifact@v4
        with:
          name: output_1
          path: output_1/

  translate2:
    name: Translate Pattern 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          cd ..
          pip install googletrans==4.0.0rc1 requests
      - run: python3 py/translate2.py
      - uses: actions/upload-artifact@v4
        with:
          name: output_2
          path: output_2/

  translate3:
    name: Translate Pattern 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          cd ..
          pip install googletrans==4.0.0rc1 requests
      - run: python3 py/translate3.py
      - uses: actions/upload-artifact@v4
        with:
          name: output_3
          path: output_3/

  translate4:
    name: Translate Pattern 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          cd ..
          pip install googletrans==4.0.0rc1 requests
      - run: python3 py/translate4.py
      - uses: actions/upload-artifact@v4
        with:
          name: output_4
          path: output_4/

  merge-results:
    name: Merge and Zip Outputs
    runs-on: ubuntu-latest
    needs: [translate1, translate2, translate3, translate4]
    steps:
      - uses: actions/checkout@v4
      - name: Download output_1 artifact
        uses: actions/download-artifact@v4
        with:
          name: output_1
          path: output_1
      - name: Download output_2 artifact
        uses: actions/download-artifact@v4
        with:
          name: output_2
          path: output_2
      - name: Download output_3 artifact
        uses: actions/download-artifact@v4
        with:
          name: output_3
          path: output_3
      - name: Download output_4 artifact
        uses: actions/download-artifact@v4
        with:
          name: output_4
          path: output_4

      - name: Combine outputs into output_translate
        run: |
          mkdir -p output_translate
          cp -r output_1/* output_translate/ || echo "output_1 empty or missing"
          cp -r output_2/* output_translate/ || echo "output_2 empty or missing"
          cp -r output_3/* output_translate/ || echo "output_3 empty or missing"
          cp -r output_4/* output_translate/ || echo "output_4 empty or missing"

      - name: Zip output_translate folder
        run: |
          zip -r output_translate.zip output_translate/

      - name: Upload combined output artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_translate
          path: output_translate.zip