name: Generate Translation RPY (TL)
on:
  workflow_dispatch:  # bisa kamu ubah ke push kalau mau otomatis

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Project Structure
        run: |
          mkdir -p game
          cp to_tl/*.rpy game/
          echo "File utama yang akan dibuatkan file TL:"
          ls -l game/

      - name: Install Ren'Py SDK
        run: |
          wget -q https://www.renpy.org/dl/8.3.4/renpy-8.3.4-sdk.tar.bz2
          tar -xf renpy-8.3.4-sdk.tar.bz2
          echo "Ren'Py SDK versi:"
          ./renpy-8.3.4-sdk/renpy.sh --version

      - name: Generate Translation Files
        run: |
          # Ganti 'indonesian' dengan bahasa target (misal: english, japanese, dst)
          ./renpy-8.3.4-sdk/renpy.sh ./game translate indonesian
          echo "Daftar file TL yang dihasilkan:"
          find game/tl -type f -name "*.rpy"

      - name: Move TL Files
        run: |
          mkdir -p to_translation_result
          cp -r game/tl/* to_translation_result/
          echo "Isi folder hasil:"
          ls -R to_translation_result/

      - uses: actions/upload-artifact@v4
        with:
          name: Translated-RPY-Files
          path: to_translation_result/**