name: Translation Pipeline - Parallel
on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Files per batch (default 3)'
        default: '3'
        required: false
      sleep_other:
        description: 'Sleep time for Google/Bing/Lingva (seconds)'
        default: '1.0'
        required: false
      sleep_shell:
        description: 'Sleep time for translate-shell (seconds)'
        default: '0.5'
        required: false

jobs:
  translate-pattern-1:
    name: Translate Pattern [1]
    runs-on: ubuntu-latest
    timeout-minutes: 350  # 5 jam 50 menit
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git python3 python3-pip
          
      - name: Install translate-shell from GitHub
        run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          
      - name: Install Python Packages
        run: |
          pip install googletrans==4.0.0rc1 requests
          
      - name: Run Translation Pattern [1]
        env:
          BATCH_SIZE: ${{ inputs.batch_size }}
          SLEEP_OTHER: ${{ inputs.sleep_other }}
          SLEEP_SHELL: ${{ inputs.sleep_shell }}
        run: |
          python py/translate1.py
          
      - name: Upload Pattern [1] Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-pattern-1
          path: output_1/
          retention-days: 7

  translate-pattern-2:
    name: Translate Pattern [2]
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git python3 python3-pip
          
      - name: Install translate-shell from GitHub
        run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          
      - name: Install Python Packages
        run: |
          pip install googletrans==4.0.0rc1 requests
          
      - name: Run Translation Pattern [2]
        env:
          BATCH_SIZE: ${{ inputs.batch_size }}
          SLEEP_OTHER: ${{ inputs.sleep_other }}
          SLEEP_SHELL: ${{ inputs.sleep_shell }}
        run: |
          python py/translate2.py
          
      - name: Upload Pattern [2] Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-pattern-2
          path: output_2/
          retention-days: 7

  translate-pattern-3:
    name: Translate Pattern [3]
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git python3 python3-pip
          
      - name: Install translate-shell from GitHub
        run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          
      - name: Install Python Packages
        run: |
          pip install googletrans==4.0.0rc1 requests
          
      - name: Run Translation Pattern [3]
        env:
          BATCH_SIZE: ${{ inputs.batch_size }}
          SLEEP_OTHER: ${{ inputs.sleep_other }}
          SLEEP_SHELL: ${{ inputs.sleep_shell }}
        run: |
          python py/translate3.py
          
      - name: Upload Pattern [3] Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-pattern-3
          path: output_3/
          retention-days: 7

  translate-pattern-4:
    name: Translate Pattern [4]
    runs-on: ubuntu-latest
    timeout-minutes: 350
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc git python3 python3-pip
          
      - name: Install translate-shell from GitHub
        run: |
          git clone https://github.com/soimort/translate-shell
          cd translate-shell
          make
          sudo make install
          
      - name: Install Python Packages
        run: |
          pip install googletrans==4.0.0rc1 requests
          
      - name: Run Translation Pattern [4]
        env:
          BATCH_SIZE: ${{ inputs.batch_size }}
          SLEEP_OTHER: ${{ inputs.sleep_other }}
          SLEEP_SHELL: ${{ inputs.sleep_shell }}
        run: |
          python py/translate4.py
          
      - name: Upload Pattern [4] Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: output-pattern-4
          path: output_4/
          retention-days: 7

  merge-results:
    name: Merge Results and Create ZIP
    runs-on: ubuntu-latest
    needs: [translate-pattern-1, translate-pattern-2, translate-pattern-3, translate-pattern-4]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Download All Artifacts
        run: |
          mkdir -p artifacts
          gh run download ${{ github.run_id }} -n output-pattern-1 -D artifacts/output_1
          gh run download ${{ github.run_id }} -n output-pattern-2 -D artifacts/output_2
          gh run download ${{ github.run_id }} -n output-pattern-3 -D artifacts/output_3
          gh run download ${{ github.run_id }} -n output-pattern-4 -D artifacts/output_4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Create Master Translate Folder
        run: |
          mkdir -p translate
          # Copy semua output yang ada (partial results jika ada job yang gagal)
          [ -d "artifacts/output_1" ] && cp -r artifacts/output_1 translate/ || echo "output_1 not found"
          [ -d "artifacts/output_2" ] && cp -r artifacts/output_2 translate/ || echo "output_2 not found"
          [ -d "artifacts/output_3" ] && cp -r artifacts/output_3 translate/ || echo "output_3 not found"
          [ -d "artifacts/output_4" ] && cp -r artifacts/output_4 translate/ || echo "output_4 not found"
          
      - name: Create ZIP Archive
        run: |
          zip -r translation_results.zip translate/
          echo "ZIP file created with contents:"
          ls -la translation_results.zip
          du -h translation_results.zip
          
      - name: Upload Final ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: translation-results
          path: translation_results.zip
          retention-days: 30

  notify-completion:
    name: Notify Completion
    runs-on: ubuntu-latest
    needs: merge-results
    if: always()
    
    steps:
      - name: Workflow Status
        run: |
          if [[ "${{ needs.translate-pattern-1.result }}" == "success" && 
                "${{ needs.translate-pattern-2.result }}" == "success" && 
                "${{ needs.translate-pattern-3.result }}" == "success" && 
                "${{ needs.translate-pattern-4.result }}" == "success" ]]; then
            echo "🎉 All translation jobs completed successfully!"
            echo "📦 ZIP artifact available for download"
          else
            echo "⚠️ Some jobs failed, but partial results are available"
            echo "✅ Successful jobs:"
            echo "   Pattern 1: ${{ needs.translate-pattern-1.result }}"
            echo "   Pattern 2: ${{ needs.translate-pattern-2.result }}"
            echo "   Pattern 3: ${{ needs.translate-pattern-3.result }}"
            echo "   Pattern 4: ${{ needs.translate-pattern-4.result }}"
          fi